// Country code to full name mapping
export const COUNTRY_NAMES: Record<string, string> = {
  // Common Winter Olympics countries
  "sui": "Switzerland",
  "ita": "Italy",
  "aut": "Austria",
  "fra": "France",
  "ger": "Germany",
  "usa": "United States",
  "can": "Canada",
  "nor": "Norway",
  "swe": "Sweden",
  "fin": "Finland",
  "jpn": "Japan",
  "chn": "China",
  "kor": "South Korea",
  "rus": "Russia",
  "pol": "Poland",
  "cze": "Czech Republic",
  "svk": "Slovakia",
  "slo": "Slovenia",
  "cro": "Croatia",
  "esp": "Spain",
  "gbr": "Great Britain",
  "ned": "Netherlands",
  "bel": "Belgium",
  "aus": "Australia",
  "nzl": "New Zealand",
  "est": "Estonia",
  "lat": "Latvia",
  "ltu": "Lithuania",
  "ukr": "Ukraine",
  "blr": "Belarus",
  "kaz": "Kazakhstan",
  "lva": "Latvia",
  "lie": "Liechtenstein",
  "and": "Andorra",
  "mon": "Monaco",
  "isr": "Israel",
  "tur": "Turkey",
  "bul": "Bulgaria",
  "rou": "Romania",
  "hun": "Hungary",
  "bih": "Bosnia and Herzegovina",
  "srb": "Serbia",
  "mne": "Montenegro",
  "mkd": "North Macedonia",
  "alb": "Albania",
  "gre": "Greece",
  "isl": "Iceland",
  "irl": "Ireland",
  "den": "Denmark",
  "lux": "Luxembourg",
  "por": "Portugal",
  "bra": "Brazil",
  "arg": "Argentina",
  "chl": "Chile",
  "mex": "Mexico",
  "col": "Colombia",
  "ven": "Venezuela",
  "ecu": "Ecuador",
  "per": "Peru",
  "ury": "Uruguay",
  "par": "Paraguay",
  "bol": "Bolivia",
  "pan": "Panama",
  "cri": "Costa Rica",
  "gtm": "Guatemala",
  "hnd": "Honduras",
  "nic": "Nicaragua",
  "slv": "El Salvador",
  "jam": "Jamaica",
  "cub": "Cuba",
  "dom": "Dominican Republic",
  "hti": "Haiti",
  "tto": "Trinidad and Tobago",
  "bhs": "Bahamas",
  "barb": "Barbados",
  "guy": "Guyana",
  "sur": "Suriname",
  "ind": "India",
  "pak": "Pakistan",
  "bgd": "Bangladesh",
  "lka": "Sri Lanka",
  "npl": "Nepal",
  "btn": "Bhutan",
  "mmr": "Myanmar",
  "tha": "Thailand",
  "vnm": "Vietnam",
  "lao": "Laos",
  "khm": "Cambodia",
  "mys": "Malaysia",
  "sgp": "Singapore",
  "idn": "Indonesia",
  "phl": "Philippines",
  "brn": "Brunei",
  "tls": "Timor-Leste",
  "afg": "Afghanistan",
  "irn": "Iran",
  "irq": "Iraq",
  "sau": "Saudi Arabia",
  "are": "United Arab Emirates",
  "qat": "Qatar",
  "kwt": "Kuwait",
  "bhr": "Bahrain",
  "omn": "Oman",
  "yem": "Yemen",
  "jor": "Jordan",
  "lbn": "Lebanon",
  "syr": "Syria",
  "pse": "Palestine",
  "cyp": "Cyprus",
  "mlt": "Malta",
  "egy": "Egypt",
  "lby": "Libya",
  "tun": "Tunisia",
  "dza": "Algeria",
  "mar": "Morocco",
  "sdn": "Sudan",
  "eth": "Ethiopia",
  "ken": "Kenya",
  "tza": "Tanzania",
  "uga": "Uganda",
  "rwa": "Rwanda",
  "bdi": "Burundi",
  "sle": "Sierra Leone",
  "gha": "Ghana",
  "nga": "Nigeria",
  "sen": "Senegal",
  "mli": "Mali",
  "bfa": "Burkina Faso",
  "ner": "Niger",
  "tcd": "Chad",
  "cmr": "Cameroon",
  "caf": "Central African Republic",
  "cog": "Republic of the Congo",
  "cod": "Democratic Republic of the Congo",
  "gab": "Gabon",
  "gnq": "Equatorial Guinea",
  "stp": "São Tomé and Príncipe",
  "ago": "Angola",
  "zmb": "Zambia",
  "zwe": "Zimbabwe",
  "bwa": "Botswana",
  "nam": "Namibia",
  "zaf": "South Africa",
  "lso": "Lesotho",
  "swz": "Eswatini",
  "mwi": "Malawi",
  "moz": "Mozambique",
  "mdg": "Madagascar",
  "mus": "Mauritius",
  "sey": "Seychelles",
  "com": "Comoros",
  "dji": "Djibouti",
  "som": "Somalia",
  "eri": "Eritrea",
  "ssd": "South Sudan",
  "geo": "Georgia",
};

/**
 * Get the full country name from a country code
 * @param code - 3-letter country code (lowercase)
 * @returns Full country name or the code if not found
 */
export function getCountryName(code: string): string {
  const normalizedCode = code.toLowerCase().trim();
  return COUNTRY_NAMES[normalizedCode] || code;
}
